CREATE TABLE IF NOT EXISTS career_stats_qb_tbl (
  player_id TEXT,
  full_name TEXT,
  position TEXT,
  recent_team TEXT,
  seasons_played INTEGER,
  games_played INTEGER,
  completions INTEGER,
  attempts INTEGER,
  passing_yards NUMERIC,
  passing_tds INTEGER,
  interceptions NUMERIC,
  sacks NUMERIC,
  sack_yards NUMERIC,
  sack_fumbles INTEGER,
  sack_fumbles_lost INTEGER,
  passing_air_yards NUMERIC,
  passing_yards_after_catch NUMERIC,
  passing_first_downs NUMERIC,
  passing_epa NUMERIC,
  passing_2pt_conversions INTEGER,
  carries INTEGER,
  rushing_yards NUMERIC,
  rushing_tds INTEGER,
  rushing_fumbles NUMERIC,
  rushing_fumbles_lost NUMERIC,
  rushing_first_downs NUMERIC,
  rushing_epa NUMERIC,
  rushing_2pt_conversions INTEGER,
  fantasy_points NUMERIC,
  fantasy_points_ppr NUMERIC,
  pacr NUMERIC,
  dakota NUMERIC
,
  PRIMARY KEY (player_id)
);

CREATE TABLE IF NOT EXISTS career_stats_rb_tbl (
  player_id TEXT,
  full_name TEXT,
  position TEXT,
  recent_team TEXT,
  seasons_played INTEGER,
  games_played INTEGER,
  carries INTEGER,
  rushing_yards NUMERIC,
  rushing_tds INTEGER,
  rushing_epa NUMERIC,
  rushing_fumbles NUMERIC,
  rushing_fumbles_lost NUMERIC,
  rushing_first_downs NUMERIC,
  rushing_2pt_conversions INTEGER,
  targets INTEGER,
  receptions INTEGER,
  receiving_yards NUMERIC,
  receiving_tds INTEGER,
  receiving_epa NUMERIC,
  receiving_fumbles NUMERIC,
  receiving_fumbles_lost NUMERIC,
  receiving_air_yards NUMERIC,
  receiving_yards_after_catch NUMERIC,
  receiving_first_downs NUMERIC,
  receiving_2pt_conversions INTEGER,
  fantasy_points NUMERIC,
  fantasy_points_ppr NUMERIC,
  racr NUMERIC,
  target_share NUMERIC,
  air_yards_share NUMERIC,
  wopr NUMERIC
);

CREATE TABLE IF NOT EXISTS career_stats_te_tbl (
  player_id TEXT,
  full_name TEXT,
  position TEXT,
  recent_team TEXT,
  seasons_played INTEGER,
  games_played INTEGER,
  targets INTEGER,
  receptions INTEGER,
  receiving_yards NUMERIC,
  receiving_tds INTEGER,
  receiving_fumbles NUMERIC,
  receiving_fumbles_lost NUMERIC,
  receiving_air_yards NUMERIC,
  receiving_yards_after_catch NUMERIC,
  receiving_first_downs NUMERIC,
  receiving_epa NUMERIC,
  receiving_2pt_conversions INTEGER,
  fantasy_points NUMERIC,
  fantasy_points_ppr NUMERIC,
  racr NUMERIC,
  target_share NUMERIC,
  air_yards_share NUMERIC,
  wopr NUMERIC
);

CREATE TABLE IF NOT EXISTS career_stats_wr_tbl (
  player_id TEXT,
  full_name TEXT,
  position TEXT,
  recent_team TEXT,
  seasons_played INTEGER,
  games_played INTEGER,
  targets INTEGER,
  receptions INTEGER,
  receiving_yards NUMERIC,
  receiving_tds INTEGER,
  receiving_fumbles NUMERIC,
  receiving_fumbles_lost NUMERIC,
  receiving_air_yards NUMERIC,
  receiving_yards_after_catch NUMERIC,
  receiving_first_downs NUMERIC,
  receiving_epa NUMERIC,
  receiving_2pt_conversions INTEGER,
  fantasy_points NUMERIC,
  fantasy_points_ppr NUMERIC,
  racr NUMERIC,
  target_share NUMERIC,
  air_yards_share NUMERIC,
  wopr NUMERIC
);

CREATE TABLE IF NOT EXISTS contracts_position_cap_pct_tbl (
  position TEXT,
  year_signed INTEGER,
  team TEXT,
  avg_apy_cap_pct NUMERIC,
  total_apy NUMERIC,
  count INTEGER
,
  PRIMARY KEY (position, year_signed, team)
);

CREATE TABLE IF NOT EXISTS contracts_qb_tbl (
  player TEXT,
  position TEXT,
  team TEXT,
  is_active BOOLEAN,
  year_signed INTEGER,
  years INTEGER,
  value NUMERIC,
  apy NUMERIC,
  guaranteed NUMERIC,
  apy_cap_pct NUMERIC,
  inflated_value NUMERIC,
  inflated_apy NUMERIC,
  inflated_guaranteed NUMERIC,
  player_page TEXT,
  otc_id TEXT,
  gsis_id TEXT,
  date_of_birth TEXT,
  height TEXT,
  weight NUMERIC,
  college TEXT,
  draft_year INTEGER,
  draft_round INTEGER,
  draft_overall INTEGER,
  draft_team TEXT,
  contract_start INTEGER,
  contract_end INTEGER,
  contract_id INTEGER,
  teams_played_for INTEGER
,
  PRIMARY KEY (contract_id)
);

CREATE TABLE IF NOT EXISTS def_player_stats_career_tbl (
  player_id TEXT,
  position TEXT,
  position_group TEXT,
  last_team TEXT,
  seasons_played INTEGER,
  games_played INTEGER,
  def_tackles INTEGER,
  def_tackles_solo INTEGER,
  def_tackle_assists INTEGER,
  def_tackles_for_loss INTEGER,
  def_tackles_for_loss_yards NUMERIC,
  def_fumbles_forced INTEGER,
  def_sacks NUMERIC,
  def_sack_yards NUMERIC,
  def_qb_hits NUMERIC,
  def_interceptions NUMERIC,
  def_interception_yards NUMERIC,
  def_pass_defended NUMERIC,
  def_tds NUMERIC,
  def_fumbles NUMERIC,
  def_fumble_recovery_own NUMERIC,
  def_fumble_recovery_yards_own NUMERIC,
  def_fumble_recovery_opp NUMERIC,
  def_fumble_recovery_yards_opp NUMERIC,
  def_safety INTEGER,
  def_penalty NUMERIC,
  def_penalty_yards NUMERIC
,
  PRIMARY KEY (player_id)
);

CREATE TABLE IF NOT EXISTS def_player_stats_season_tbl (
  season INTEGER,
  player_id TEXT,
  team TEXT,
  position TEXT,
  position_group TEXT,
  games_played INTEGER,
  def_tackles INTEGER,
  def_tackles_solo INTEGER,
  def_tackle_assists INTEGER,
  def_tackles_for_loss INTEGER,
  def_tackles_for_loss_yards NUMERIC,
  def_fumbles_forced INTEGER,
  def_sacks NUMERIC,
  def_sack_yards NUMERIC,
  def_qb_hits NUMERIC,
  def_interceptions NUMERIC,
  def_interception_yards NUMERIC,
  def_pass_defended NUMERIC,
  def_tds NUMERIC,
  def_fumbles NUMERIC,
  def_fumble_recovery_own NUMERIC,
  def_fumble_recovery_yards_own NUMERIC,
  def_fumble_recovery_opp NUMERIC,
  def_fumble_recovery_yards_opp NUMERIC,
  def_safety INTEGER,
  def_penalty NUMERIC,
  def_penalty_yards NUMERIC
,
  PRIMARY KEY (season, player_id)
);

CREATE TABLE IF NOT EXISTS def_player_stats_weekly_tbl (
  season INTEGER,
  week INTEGER,
  season_type TEXT,
  player_id TEXT,
  team TEXT,
  position TEXT,
  position_group TEXT,
  def_tackles INTEGER,
  def_tackles_solo INTEGER,
  def_tackle_assists INTEGER,
  def_tackles_for_loss INTEGER,
  def_tackles_for_loss_yards NUMERIC,
  def_fumbles_forced INTEGER,
  def_sacks NUMERIC,
  def_sack_yards NUMERIC,
  def_qb_hits NUMERIC,
  def_interceptions NUMERIC,
  def_interception_yards NUMERIC,
  def_pass_defended NUMERIC,
  def_tds NUMERIC,
  def_fumbles NUMERIC,
  def_fumble_recovery_own NUMERIC,
  def_fumble_recovery_yards_own NUMERIC,
  def_fumble_recovery_opp NUMERIC,
  def_fumble_recovery_yards_opp NUMERIC,
  def_safety INTEGER,
  def_penalty NUMERIC,
  def_penalty_yards NUMERIC
,
  PRIMARY KEY (season, week, season_type, player_id)
);

CREATE TABLE IF NOT EXISTS def_team_stats_season_tbl (
  season INTEGER,
  team TEXT,
  n_players INTEGER,
  def_tackles INTEGER,
  def_tackles_solo INTEGER,
  def_tackle_assists INTEGER,
  def_tackles_for_loss INTEGER,
  def_tackles_for_loss_yards NUMERIC,
  def_fumbles_forced INTEGER,
  def_sacks NUMERIC,
  def_sack_yards NUMERIC,
  def_qb_hits NUMERIC,
  def_interceptions NUMERIC,
  def_interception_yards NUMERIC,
  def_pass_defended NUMERIC,
  def_tds NUMERIC,
  def_fumbles NUMERIC,
  def_fumble_recovery_own NUMERIC,
  def_fumble_recovery_yards_own NUMERIC,
  def_fumble_recovery_opp NUMERIC,
  def_fumble_recovery_yards_opp NUMERIC,
  def_safety INTEGER,
  def_penalty NUMERIC,
  def_penalty_yards NUMERIC
,
  PRIMARY KEY (season, team)
);

CREATE TABLE IF NOT EXISTS depth_charts_player_starts_tbl (
  season INTEGER,
  team TEXT,
  position TEXT,
  gsis_id TEXT,
  total_starts INTEGER
,
  PRIMARY KEY (season, team, position)
);

CREATE TABLE IF NOT EXISTS depth_charts_position_stability_tbl (
  season INTEGER,
  week INTEGER,
  team TEXT,
  position TEXT,
  position_group_score NUMERIC
,
  PRIMARY KEY (season, week, team, position)
);

CREATE TABLE IF NOT EXISTS depth_charts_qb_team_tbl (
  season INTEGER,
  week INTEGER,
  team TEXT,
  distinct_qb_starters INTEGER
,
  PRIMARY KEY (season, week, team)
);

CREATE TABLE IF NOT EXISTS depth_charts_starters_tbl (
  season INTEGER,
  week INTEGER,
  team TEXT,
  player TEXT,
  position TEXT,
  gsis_id TEXT,
  position_group TEXT,
  player_starts INTEGER,
  is_new_starter BOOLEAN
,
  PRIMARY KEY (season, week, team)
);

CREATE TABLE IF NOT EXISTS games_tbl (
  game_id TEXT,
  season INTEGER,
  week INTEGER,
  game_type TEXT,
  kickoff TEXT,
  weekday TEXT,
  home_team TEXT,
  away_team TEXT,
  home_score INTEGER,
  away_score INTEGER,
  result TEXT,
  favored_team TEXT,
  overtime BOOLEAN,
  stadium TEXT,
  stadium_id TEXT,
  roof TEXT,
  surface TEXT,
  temp INTEGER,
  wind INTEGER,
  referee TEXT,
  home_qb_id TEXT,
  away_qb_id TEXT,
  home_qb_name TEXT,
  away_qb_name TEXT,
  home_coach TEXT,
  away_coach TEXT,
  div_game BOOLEAN,
  spread_line NUMERIC,
  total_line NUMERIC,
  away_moneyline INTEGER,
  home_moneyline INTEGER,
  away_spread_odds INTEGER,
  home_spread_odds INTEGER,
  under_odds INTEGER,
  over_odds INTEGER,
  old_game_id TEXT,
  gsis TEXT,
  nfl_detail_id TEXT,
  pfr TEXT,
  pff TEXT,
  espn TEXT,
  ftn TEXT
,
  PRIMARY KEY (game_id)
);

CREATE TABLE IF NOT EXISTS injuries_position_weekly_tbl (
  season INTEGER,
  week INTEGER,
  team TEXT,
  position TEXT,
  position_injuries INTEGER,
  cumulative_position_injuries INTEGER
,
  PRIMARY KEY (season, week, team, position)
);

CREATE TABLE IF NOT EXISTS injuries_team_season_tbl (
  season INTEGER,
  team TEXT,
  season_injuries INTEGER
,
  PRIMARY KEY (season, team)
);

CREATE TABLE IF NOT EXISTS injuries_team_weekly_tbl (
  season INTEGER,
  week INTEGER,
  team TEXT,
  weekly_injuries INTEGER,
  cumulative_injuries INTEGER
,
  PRIMARY KEY (season, week, team)
);

CREATE TABLE IF NOT EXISTS injuries_weekly_tbl (
  season INTEGER,
  week INTEGER,
  team TEXT,
  gsis_id TEXT,
  full_name TEXT,
  position TEXT,
  report_status TEXT,
  injury_reported BOOLEAN,
  did_not_practice BOOLEAN,
  injury_status TEXT,
  practice_status TEXT,
  primary_injury TEXT,
  secondary_injury BOOLEAN
,
  PRIMARY KEY (season, week, team, gsis_id)
);

CREATE TABLE IF NOT EXISTS nextgen_stats_player_career_tbl (
  player_gsis_id TEXT,
  team_abbr TEXT,
  player_position TEXT,
  games_played INTEGER,
  attempts INTEGER,
  completions INTEGER,
  pass_yards INTEGER,
  pass_touchdowns INTEGER,
  interceptions INTEGER,
  avg_attempts NUMERIC,
  avg_completions NUMERIC,
  avg_pass_yards NUMERIC,
  avg_pass_touchdowns NUMERIC,
  avg_interceptions NUMERIC,
  avg_time_to_throw NUMERIC,
  avg_completed_air_yards NUMERIC,
  avg_intended_air_yards NUMERIC,
  avg_air_yards_differential NUMERIC,
  aggressiveness NUMERIC,
  max_completed_air_distance NUMERIC,
  avg_air_yards_to_sticks NUMERIC,
  completion_percentage NUMERIC,
  expected_completion_percentage NUMERIC,
  completion_percentage_above_expectation NUMERIC,
  avg_air_distance NUMERIC,
  max_air_distance NUMERIC,
  passer_rating NUMERIC
,
  PRIMARY KEY (player_gsis_id)
);

CREATE TABLE IF NOT EXISTS nextgen_stats_player_postseason_tbl (
  player_gsis_id TEXT,
  team_abbr TEXT,
  player_position TEXT,
  games_played INTEGER,
  attempts INTEGER,
  completions INTEGER,
  pass_yards INTEGER,
  pass_touchdowns INTEGER,
  interceptions INTEGER,
  avg_attempts NUMERIC,
  avg_completions NUMERIC,
  avg_pass_yards NUMERIC,
  avg_pass_touchdowns NUMERIC,
  avg_interceptions NUMERIC,
  avg_time_to_throw NUMERIC,
  avg_completed_air_yards NUMERIC,
  avg_intended_air_yards NUMERIC,
  avg_air_yards_differential NUMERIC,
  aggressiveness NUMERIC,
  max_completed_air_distance NUMERIC,
  avg_air_yards_to_sticks NUMERIC,
  completion_percentage NUMERIC,
  expected_completion_percentage NUMERIC,
  completion_percentage_above_expectation NUMERIC,
  avg_air_distance NUMERIC,
  max_air_distance NUMERIC,
  passer_rating NUMERIC
,
  PRIMARY KEY (player_gsis_id)
);

CREATE TABLE IF NOT EXISTS nextgen_stats_player_season_tbl (
  season INTEGER,
  player_gsis_id TEXT,
  team_abbr TEXT,
  player_position TEXT,
  games_played INTEGER,
  attempts INTEGER,
  completions INTEGER,
  pass_yards INTEGER,
  pass_touchdowns INTEGER,
  interceptions INTEGER,
  avg_attempts NUMERIC,
  avg_completions NUMERIC,
  avg_pass_yards NUMERIC,
  avg_pass_touchdowns NUMERIC,
  avg_interceptions NUMERIC,
  avg_time_to_throw NUMERIC,
  avg_completed_air_yards NUMERIC,
  avg_intended_air_yards NUMERIC,
  avg_air_yards_differential NUMERIC,
  aggressiveness NUMERIC,
  max_completed_air_distance NUMERIC,
  avg_air_yards_to_sticks NUMERIC,
  completion_percentage NUMERIC,
  expected_completion_percentage NUMERIC,
  completion_percentage_above_expectation NUMERIC,
  avg_air_distance NUMERIC,
  max_air_distance NUMERIC,
  passer_rating NUMERIC
,
  PRIMARY KEY (season, player_gsis_id)
);

CREATE TABLE IF NOT EXISTS nextgen_stats_player_weekly_tbl (
  season INTEGER,
  season_type TEXT,
  week INTEGER,
  player_gsis_id TEXT,
  team_abbr TEXT,
  player_position TEXT,
  avg_time_to_throw NUMERIC,
  avg_completed_air_yards NUMERIC,
  avg_intended_air_yards NUMERIC,
  avg_air_yards_differential NUMERIC,
  aggressiveness NUMERIC,
  max_completed_air_distance NUMERIC,
  avg_air_yards_to_sticks NUMERIC,
  attempts INTEGER,
  completions INTEGER,
  pass_yards INTEGER,
  pass_touchdowns INTEGER,
  interceptions INTEGER,
  passer_rating NUMERIC,
  completion_percentage NUMERIC,
  expected_completion_percentage NUMERIC,
  completion_percentage_above_expectation NUMERIC,
  avg_air_distance NUMERIC,
  max_air_distance NUMERIC
,
  PRIMARY KEY (season, season_type, week, player_gsis_id)
);

CREATE TABLE IF NOT EXISTS participation_defense_game_tbl (
  game_id TEXT,
  defense_team TEXT,
  season INTEGER,
  week INTEGER,
  n_plays INTEGER,
  n_pass INTEGER,
  n_run INTEGER,
  n_low_rush INTEGER,
  n_standard_rush INTEGER,
  n_blitz INTEGER,
  n_heavy_blitz INTEGER,
  n_light_box INTEGER,
  n_standard_box INTEGER,
  n_stacked_box INTEGER,
  n_man INTEGER,
  n_zone INTEGER,
  n_cover_0 INTEGER,
  n_cover_1 INTEGER,
  n_cover_2 INTEGER,
  n_cover_3 INTEGER,
  n_cover_4 INTEGER,
  n_cover_6 INTEGER,
  n_cover_2_man INTEGER,
  n_prevent INTEGER,
  n_pressures INTEGER,
  avg_time_to_throw NUMERIC,
  cumulative_plays INTEGER,
  cumulative_pass INTEGER,
  cumulative_run INTEGER,
  cumulative_low_rush INTEGER,
  cumulative_standard_rush INTEGER,
  cumulative_blitz INTEGER,
  cumulative_heavy_blitz INTEGER,
  cumulative_light_box INTEGER,
  cumulative_standard_box INTEGER,
  cumulative_stacked_box INTEGER,
  cumulative_man INTEGER,
  cumulative_zone INTEGER,
  cumulative_cover_0 INTEGER,
  cumulative_cover_1 INTEGER,
  cumulative_cover_2 INTEGER,
  cumulative_cover_3 INTEGER,
  cumulative_cover_4 INTEGER,
  cumulative_cover_6 INTEGER,
  cumulative_cover_2_man INTEGER,
  cumulative_prevent INTEGER,
  cumulative_pressures INTEGER,
  avg_time_to_throw_to_date NUMERIC
,
  PRIMARY KEY (game_id, defense_team)
);

CREATE TABLE IF NOT EXISTS participation_defense_pbp_tbl (
  game_id TEXT,
  play_id INTEGER,
  season INTEGER,
  week INTEGER,
  defense_team TEXT,
  play_type TEXT,
  possession_team TEXT,
  defense_personnel TEXT,
  defenders_in_box INTEGER,
  number_of_pass_rushers INTEGER,
  defense_man_zone_type TEXT,
  defense_coverage_type TEXT,
  time_to_throw NUMERIC,
  was_pressure BOOLEAN,
  team1 TEXT,
  team2 TEXT,
  rush_bin TEXT,
  box_bin TEXT,
  cumulative_pass INTEGER,
  cumulative_run INTEGER,
  cumulative_low_rush INTEGER,
  cumulative_standard_rush INTEGER,
  cumulative_blitz INTEGER,
  cumulative_heavy_blitz INTEGER,
  cumulative_light_box INTEGER,
  cumulative_standard_box INTEGER,
  cumulative_stacked_box INTEGER,
  cumulative_man INTEGER,
  cumulative_zone INTEGER,
  cumulative_cover_0 INTEGER,
  cumulative_cover_1 INTEGER,
  cumulative_cover_2 INTEGER,
  cumulative_cover_3 INTEGER,
  cumulative_cover_4 INTEGER,
  cumulative_cover_6 INTEGER,
  cumulative_cover_2_man INTEGER,
  cumulative_prevent INTEGER
,
  PRIMARY KEY (game_id, play_id)
);

CREATE TABLE IF NOT EXISTS participation_defense_season_tbl (
  season INTEGER,
  defense_team TEXT,
  n_plays INTEGER,
  n_pass INTEGER,
  n_run INTEGER,
  n_low_rush INTEGER,
  n_standard_rush INTEGER,
  n_blitz INTEGER,
  n_heavy_blitz INTEGER,
  n_light_box INTEGER,
  n_standard_box INTEGER,
  n_stacked_box INTEGER,
  n_man INTEGER,
  n_zone INTEGER,
  n_cover_0 INTEGER,
  n_cover_1 INTEGER,
  n_cover_2 INTEGER,
  n_cover_3 INTEGER,
  n_cover_4 INTEGER,
  n_cover_6 INTEGER,
  n_cover_2_man INTEGER,
  n_prevent INTEGER,
  n_pressures INTEGER,
  avg_time_to_throw NUMERIC
,
  PRIMARY KEY (season, defense_team)
);

CREATE TABLE IF NOT EXISTS participation_offense_game_tbl (
  game_id TEXT,
  team TEXT,
  season INTEGER,
  week INTEGER,
  n_plays INTEGER,
  n_pass INTEGER,
  n_run INTEGER,
  n_empty INTEGER,
  n_i_form INTEGER,
  n_jumbo INTEGER,
  n_pistol INTEGER,
  n_shotgun INTEGER,
  n_singleback INTEGER,
  n_wildcat INTEGER,
  n_other_formations INTEGER,
  n_angle INTEGER,
  n_corner INTEGER,
  n_cross INTEGER,
  n_flat INTEGER,
  n_go INTEGER,
  n_hitch INTEGER,
  n_in INTEGER,
  n_out INTEGER,
  n_post INTEGER,
  n_screen INTEGER,
  n_slant INTEGER,
  n_wheel INTEGER,
  n_other_routes INTEGER,
  avg_time_to_throw NUMERIC,
  pressures_allowed INTEGER,
  cumulative_plays INTEGER,
  cumulative_pass INTEGER,
  cumulative_run INTEGER,
  cumulative_pressures_allowed INTEGER,
  cumulative_screen INTEGER,
  cumulative_flat INTEGER,
  cumulative_other_routes INTEGER,
  avg_time_to_throw_to_date NUMERIC
,
  PRIMARY KEY (game_id, team)
);

CREATE TABLE IF NOT EXISTS participation_offense_pbp_tbl (
  game_id TEXT,
  play_id INTEGER,
  season INTEGER,
  week INTEGER,
  team TEXT,
  play_type TEXT,
  offense_formation TEXT,
  offense_personnel TEXT,
  n_offense INTEGER,
  ngs_air_yards NUMERIC,
  time_to_throw NUMERIC,
  was_pressure BOOLEAN,
  route TEXT,
  pressures_allowed INTEGER
,
  PRIMARY KEY (game_id, play_id)
);

CREATE TABLE IF NOT EXISTS participation_offense_season_tbl (
  season INTEGER,
  team TEXT,
  n_plays INTEGER,
  n_pass INTEGER,
  n_run INTEGER,
  n_empty INTEGER,
  n_i_form INTEGER,
  n_jumbo INTEGER,
  n_pistol INTEGER,
  n_shotgun INTEGER,
  n_singleback INTEGER,
  n_wildcat INTEGER,
  n_other_formations INTEGER,
  n_angle INTEGER,
  n_corner INTEGER,
  n_cross INTEGER,
  n_flat INTEGER,
  n_go INTEGER,
  n_hitch INTEGER,
  n_in INTEGER,
  n_out INTEGER,
  n_post INTEGER,
  n_screen INTEGER,
  n_slant INTEGER,
  n_wheel INTEGER,
  n_other_routes INTEGER,
  avg_time_to_throw NUMERIC,
  pressures_allowed INTEGER
,
  PRIMARY KEY (season, team)
);

CREATE TABLE IF NOT EXISTS pbp_tbl (
  game_id TEXT,
  play_id INTEGER,
  qtr INTEGER,
  down INTEGER,
  ydstogo INTEGER,
  yardline_100 INTEGER,
  posteam TEXT,
  defteam TEXT,
  play_type TEXT,
  epa NUMERIC,
  success INTEGER,
  touchdown INTEGER,
  interception INTEGER,
  penalty INTEGER,
  pass INTEGER,
  rush INTEGER,
  special INTEGER,
  cumulative_epa_offense NUMERIC,
  cumulative_success_offense INTEGER,
  cumulative_td_offense INTEGER,
  cumulative_int_offense INTEGER,
  cumulative_penalty_offense INTEGER,
  cumulative_epa_defense NUMERIC,
  cumulative_success_defense INTEGER,
  cumulative_td_allowed INTEGER,
  cumulative_int_defense INTEGER,
  cumulative_penalty_defense INTEGER
,
  PRIMARY KEY (game_id, play_id)
);

CREATE TABLE IF NOT EXISTS roster_position_summary_tbl (
  season INTEGER,
  team TEXT,
  position TEXT,
  n_players INTEGER,
  avg_age NUMERIC,
  avg_height NUMERIC,
  avg_weight NUMERIC,
  avg_exp NUMERIC
,
  PRIMARY KEY (season, team, position)
);

CREATE TABLE IF NOT EXISTS roster_summary_tbl (
  season INTEGER,
  team TEXT,
  n_players INTEGER,
  avg_age NUMERIC,
  avg_height NUMERIC,
  avg_weight NUMERIC,
  avg_exp NUMERIC
,
  PRIMARY KEY (season, team)
);

CREATE TABLE IF NOT EXISTS rosters_tbl (
  player_id TEXT,
  team_id TEXT,
  season INTEGER,
  week INTEGER,
  full_name TEXT,
  first_name TEXT,
  last_name TEXT,
  position TEXT,
  status TEXT,
  age NUMERIC,
  height INTEGER,
  weight INTEGER,
  college TEXT,
  years_exp INTEGER,
  rookie_year INTEGER,
  entry_year INTEGER,
  headshot_url TEXT,
  esb_id TEXT
,
  PRIMARY KEY (player_id, team_id, season, week)
);

CREATE TABLE IF NOT EXISTS season_results_tbl (
  season INTEGER,
  team_id TEXT,
  wins INTEGER,
  losses INTEGER,
  ties INTEGER,
  points_for INTEGER,
  points_against INTEGER,
  point_diff INTEGER,
  made_playoffs BOOLEAN,
  postseason_round TEXT
,
  PRIMARY KEY (season, team_id)
);

CREATE TABLE IF NOT EXISTS season_stats_qb_tbl (
  season INTEGER,
  player_id TEXT,
  full_name TEXT,
  position TEXT,
  recent_team TEXT,
  games_played INTEGER,
  completions INTEGER,
  attempts INTEGER,
  passing_yards NUMERIC,
  passing_tds INTEGER,
  interceptions NUMERIC,
  sacks NUMERIC,
  sack_yards NUMERIC,
  sack_fumbles INTEGER,
  sack_fumbles_lost INTEGER,
  passing_air_yards NUMERIC,
  passing_yards_after_catch NUMERIC,
  passing_first_downs NUMERIC,
  passing_epa NUMERIC,
  passing_2pt_conversions INTEGER,
  carries INTEGER,
  rushing_yards NUMERIC,
  rushing_tds INTEGER,
  rushing_fumbles NUMERIC,
  rushing_fumbles_lost NUMERIC,
  rushing_first_downs NUMERIC,
  rushing_epa NUMERIC,
  rushing_2pt_conversions INTEGER,
  fantasy_points NUMERIC,
  fantasy_points_ppr NUMERIC,
  pacr NUMERIC,
  dakota NUMERIC
,
  PRIMARY KEY (season, player_id)
);

CREATE TABLE IF NOT EXISTS season_stats_rb_tbl (
  season INTEGER,
  player_id TEXT,
  full_name TEXT,
  position TEXT,
  recent_team TEXT,
  games_played INTEGER,
  carries INTEGER,
  rushing_yards NUMERIC,
  rushing_tds INTEGER,
  rushing_epa NUMERIC,
  rushing_fumbles NUMERIC,
  rushing_fumbles_lost NUMERIC,
  rushing_first_downs NUMERIC,
  rushing_2pt_conversions INTEGER,
  targets INTEGER,
  receptions INTEGER,
  receiving_yards NUMERIC,
  receiving_tds INTEGER,
  receiving_epa NUMERIC,
  receiving_fumbles NUMERIC,
  receiving_fumbles_lost NUMERIC,
  receiving_air_yards NUMERIC,
  receiving_yards_after_catch NUMERIC,
  receiving_first_downs NUMERIC,
  receiving_2pt_conversions INTEGER,
  fantasy_points NUMERIC,
  fantasy_points_ppr NUMERIC,
  racr NUMERIC,
  target_share NUMERIC,
  air_yards_share NUMERIC,
  wopr NUMERIC
,
  PRIMARY KEY (season, player_id)
);

CREATE TABLE IF NOT EXISTS season_stats_te_tbl (
  season INTEGER,
  player_id TEXT,
  full_name TEXT,
  position TEXT,
  recent_team TEXT,
  games_played INTEGER,
  targets INTEGER,
  receptions INTEGER,
  receiving_yards NUMERIC,
  receiving_tds INTEGER,
  receiving_fumbles NUMERIC,
  receiving_fumbles_lost NUMERIC,
  receiving_air_yards NUMERIC,
  receiving_yards_after_catch NUMERIC,
  receiving_first_downs NUMERIC,
  receiving_epa NUMERIC,
  receiving_2pt_conversions INTEGER,
  fantasy_points NUMERIC,
  fantasy_points_ppr NUMERIC,
  racr NUMERIC,
  target_share NUMERIC,
  air_yards_share NUMERIC,
  wopr NUMERIC
,
  PRIMARY KEY (season, player_id)
);

CREATE TABLE IF NOT EXISTS season_stats_wr_tbl (
  season INTEGER,
  player_id TEXT,
  full_name TEXT,
  position TEXT,
  recent_team TEXT,
  games_played INTEGER,
  targets INTEGER,
  receptions INTEGER,
  receiving_yards NUMERIC,
  receiving_tds INTEGER,
  receiving_fumbles NUMERIC,
  receiving_fumbles_lost NUMERIC,
  receiving_air_yards NUMERIC,
  receiving_yards_after_catch NUMERIC,
  receiving_first_downs NUMERIC,
  receiving_epa NUMERIC,
  receiving_2pt_conversions INTEGER,
  fantasy_points NUMERIC,
  fantasy_points_ppr NUMERIC,
  racr NUMERIC,
  target_share NUMERIC,
  air_yards_share NUMERIC,
  wopr NUMERIC
,
  PRIMARY KEY (season, player_id)
);

CREATE TABLE IF NOT EXISTS st_player_stats_season_tbl (
  season INTEGER,
  player_id TEXT,
  player_name TEXT,
  team TEXT,
  position TEXT,
  games_played INTEGER,
  fg_att INTEGER,
  fg_made INTEGER,
  fg_missed INTEGER,
  fg_blocked INTEGER,
  fg_pct NUMERIC,
  fg_long NUMERIC,
  fg_made_0_19 INTEGER,
  fg_made_20_29 INTEGER,
  fg_made_30_39 INTEGER,
  fg_made_40_49 INTEGER,
  fg_made_50_59 INTEGER,
  fg_made_60 INTEGER,
  fg_missed_0_19 INTEGER,
  fg_missed_20_29 INTEGER,
  fg_missed_30_39 INTEGER,
  fg_missed_40_49 INTEGER,
  fg_missed_50_59 INTEGER,
  fg_missed_60 INTEGER,
  fg_made_distance NUMERIC,
  fg_missed_distance NUMERIC,
  fg_blocked_distance NUMERIC,
  pat_att INTEGER,
  pat_made INTEGER,
  pat_missed INTEGER,
  pat_blocked INTEGER,
  pat_pct NUMERIC,
  gwfg_att INTEGER,
  gwfg_distance NUMERIC,
  gwfg_made INTEGER,
  gwfg_missed INTEGER,
  gwfg_blocked INTEGER
,
  PRIMARY KEY (season, player_id)
);

CREATE TABLE IF NOT EXISTS st_player_stats_weekly_tbl (
  season INTEGER,
  week INTEGER,
  season_type TEXT,
  player_id TEXT,
  player_name TEXT,
  position TEXT,
  team TEXT,
  fg_made INTEGER,
  fg_att INTEGER,
  fg_made_0_19 INTEGER,
  fg_made_20_29 INTEGER,
  fg_made_30_39 INTEGER,
  fg_made_40_49 INTEGER,
  fg_made_50_59 INTEGER,
  fg_made_60 INTEGER,
  fg_missed_0_19 INTEGER,
  fg_missed_20_29 INTEGER,
  fg_missed_30_39 INTEGER,
  fg_missed_40_49 INTEGER,
  fg_missed_50_59 INTEGER,
  fg_missed_60 INTEGER,
  cumulative_fg_made INTEGER,
  cumulative_fg_att INTEGER,
  cumulative_fg_made_0_19 INTEGER,
  cumulative_fg_made_20_29 INTEGER,
  cumulative_fg_made_30_39 INTEGER,
  cumulative_fg_made_40_49 INTEGER,
  cumulative_fg_made_50_59 INTEGER,
  cumulative_fg_made_60 INTEGER,
  cumulative_fg_missed_0_19 INTEGER,
  cumulative_fg_missed_20_29 INTEGER,
  cumulative_fg_missed_30_39 INTEGER,
  cumulative_fg_missed_40_49 INTEGER,
  cumulative_fg_missed_50_59 INTEGER,
  cumulative_fg_missed_60 INTEGER
,
  PRIMARY KEY (season, week, season_type)
);

CREATE TABLE IF NOT EXISTS weekly_results_tbl (
  season INTEGER,
  week INTEGER,
  season_type TEXT,
  team_id TEXT,
  game_id TEXT,
  date DATE,
  opponent TEXT,
  points_scored INTEGER,
  points_allowed INTEGER,
  location TEXT,
  wins_entering INTEGER,
  losses_entering INTEGER,
  ties_entering INTEGER,
  points_scored_ytd NUMERIC,
  points_allowed_ytd NUMERIC,
  point_diff_ytd NUMERIC,
  week_label TEXT
,
  PRIMARY KEY (season, team_id, week)
);

CREATE TABLE IF NOT EXISTS weekly_stats_qb_tbl (
  season INTEGER,
  week INTEGER,
  season_type TEXT,
  player_id TEXT,
  full_name TEXT,
  position TEXT,
  recent_team TEXT,
  opponent_team TEXT,
  completions INTEGER,
  attempts INTEGER,
  passing_yards NUMERIC,
  passing_tds INTEGER,
  interceptions NUMERIC,
  sacks NUMERIC,
  sack_yards NUMERIC,
  sack_fumbles INTEGER,
  sack_fumbles_lost INTEGER,
  passing_air_yards NUMERIC,
  passing_yards_after_catch NUMERIC,
  passing_first_downs NUMERIC,
  passing_epa NUMERIC,
  passing_2pt_conversions INTEGER,
  pacr NUMERIC,
  dakota NUMERIC,
  carries INTEGER,
  rushing_yards NUMERIC,
  rushing_tds INTEGER,
  rushing_fumbles NUMERIC,
  rushing_fumbles_lost NUMERIC,
  rushing_first_downs NUMERIC,
  rushing_epa NUMERIC,
  rushing_2pt_conversions INTEGER,
  fantasy_points NUMERIC,
  fantasy_points_ppr NUMERIC,
  cumulative_completions NUMERIC,
  cumulative_attempts NUMERIC,
  cumulative_passing_yards NUMERIC,
  cumulative_passing_tds NUMERIC,
  cumulative_interceptions NUMERIC,
  cumulative_sacks NUMERIC,
  cumulative_sack_yards NUMERIC,
  cumulative_passing_epa NUMERIC,
  cumulative_rushing_yards NUMERIC,
  cumulative_rushing_tds NUMERIC,
  cumulative_rushing_epa NUMERIC,
  cumulative_fantasy_points NUMERIC,
  cumulative_fantasy_points_ppr NUMERIC
,
  PRIMARY KEY (season, week, player_id)
);

CREATE TABLE IF NOT EXISTS weekly_stats_rb_tbl (
  season INTEGER,
  week INTEGER,
  season_type TEXT,
  player_id TEXT,
  full_name TEXT,
  position TEXT,
  recent_team TEXT,
  opponent_team TEXT,
  carries INTEGER,
  rushing_yards NUMERIC,
  rushing_tds INTEGER,
  rushing_fumbles NUMERIC,
  rushing_fumbles_lost NUMERIC,
  rushing_first_downs NUMERIC,
  rushing_epa NUMERIC,
  rushing_2pt_conversions INTEGER,
  targets INTEGER,
  receptions INTEGER,
  receiving_yards NUMERIC,
  receiving_tds INTEGER,
  receiving_fumbles NUMERIC,
  receiving_fumbles_lost NUMERIC,
  receiving_air_yards NUMERIC,
  receiving_yards_after_catch NUMERIC,
  receiving_first_downs NUMERIC,
  receiving_epa NUMERIC,
  receiving_2pt_conversions INTEGER,
  racr NUMERIC,
  target_share NUMERIC,
  air_yards_share NUMERIC,
  wopr NUMERIC,
  fantasy_points NUMERIC,
  fantasy_points_ppr NUMERIC,
  cumulative_carries NUMERIC,
  cumulative_rushing_yards NUMERIC,
  cumulative_rushing_tds NUMERIC,
  cumulative_rushing_epa NUMERIC,
  cumulative_targets NUMERIC,
  cumulative_receptions NUMERIC,
  cumulative_receiving_yards NUMERIC,
  cumulative_receiving_tds NUMERIC,
  cumulative_receiving_epa NUMERIC,
  cumulative_fantasy_points NUMERIC,
  cumulative_fantasy_points_ppr NUMERIC
,
  PRIMARY KEY (season, week, player_id)
);

CREATE TABLE IF NOT EXISTS weekly_stats_te_tbl (
  season INTEGER,
  week INTEGER,
  season_type TEXT,
  player_id TEXT,
  full_name TEXT,
  position TEXT,
  recent_team TEXT,
  opponent_team TEXT,
  targets INTEGER,
  receptions INTEGER,
  receiving_yards NUMERIC,
  receiving_tds INTEGER,
  receiving_fumbles NUMERIC,
  receiving_fumbles_lost NUMERIC,
  receiving_air_yards NUMERIC,
  receiving_yards_after_catch NUMERIC,
  receiving_first_downs NUMERIC,
  receiving_epa NUMERIC,
  receiving_2pt_conversions INTEGER,
  racr NUMERIC,
  target_share NUMERIC,
  air_yards_share NUMERIC,
  wopr NUMERIC,
  carries INTEGER,
  rushing_yards NUMERIC,
  rushing_tds INTEGER,
  rushing_fumbles NUMERIC,
  rushing_fumbles_lost NUMERIC,
  rushing_first_downs NUMERIC,
  rushing_epa NUMERIC,
  rushing_2pt_conversions INTEGER,
  fantasy_points NUMERIC,
  fantasy_points_ppr NUMERIC,
  cumulative_targets NUMERIC,
  cumulative_receptions NUMERIC,
  cumulative_receiving_yards NUMERIC,
  cumulative_receiving_tds NUMERIC,
  cumulative_receiving_epa NUMERIC,
  cumulative_carries NUMERIC,
  cumulative_rushing_yards NUMERIC,
  cumulative_rushing_tds NUMERIC,
  cumulative_rushing_epa NUMERIC,
  cumulative_fantasy_points NUMERIC,
  cumulative_fantasy_points_ppr NUMERIC
,
  PRIMARY KEY (season, week, player_id, position)
);

CREATE TABLE IF NOT EXISTS weekly_stats_wr_tbl (
  season INTEGER,
  week INTEGER,
  season_type TEXT,
  player_id TEXT,
  full_name TEXT,
  position TEXT,
  recent_team TEXT,
  opponent_team TEXT,
  targets INTEGER,
  receptions INTEGER,
  receiving_yards NUMERIC,
  receiving_tds INTEGER,
  receiving_fumbles NUMERIC,
  receiving_fumbles_lost NUMERIC,
  receiving_air_yards NUMERIC,
  receiving_yards_after_catch NUMERIC,
  receiving_first_downs NUMERIC,
  receiving_epa NUMERIC,
  receiving_2pt_conversions INTEGER,
  racr NUMERIC,
  target_share NUMERIC,
  air_yards_share NUMERIC,
  wopr NUMERIC,
  carries INTEGER,
  rushing_yards NUMERIC,
  rushing_tds INTEGER,
  rushing_fumbles NUMERIC,
  rushing_fumbles_lost NUMERIC,
  rushing_first_downs NUMERIC,
  rushing_epa NUMERIC,
  rushing_2pt_conversions INTEGER,
  fantasy_points NUMERIC,
  fantasy_points_ppr NUMERIC,
  cumulative_targets NUMERIC,
  cumulative_receptions NUMERIC,
  cumulative_receiving_yards NUMERIC,
  cumulative_receiving_tds NUMERIC,
  cumulative_receiving_epa NUMERIC,
  cumulative_carries NUMERIC,
  cumulative_rushing_yards NUMERIC,
  cumulative_rushing_tds NUMERIC,
  cumulative_rushing_epa NUMERIC,
  cumulative_fantasy_points NUMERIC,
  cumulative_fantasy_points_ppr NUMERIC
,
  PRIMARY KEY (season, week, player_id, position)
);
