erDiagram
    %% CORE ENTITIES
    PLAYERS ||--o{ ROSTERS : on_roster
    PLAYERS ||--o{ QB_STATS_WEEKLY : has_weekly_stats
    PLAYERS ||--o{ RB_STATS_WEEKLY : has_weekly_stats
    PLAYERS ||--o{ WRTE_STATS_WEEKLY : has_weekly_stats
    PLAYERS ||--o{ DEF_STATS_WEEKLY : has_weekly_stats
    PLAYERS ||--o{ STATS_SPECIAL_WEEKLY : has_special_stats
    PLAYERS ||--o{ NEXTGEN_STATS_WEEKLY : tracked_by
    PLAYERS ||--o{ QB_STATS_SEASON : has_season_stats
    PLAYERS ||--o{ QB_STATS_CAREER : has_career_stats
    PLAYERS ||--o{ RB_STATS_SEASON : has_season_stats
    PLAYERS ||--o{ RB_STATS_CAREER : has_career_stats
    PLAYERS ||--o{ WRTE_STATS_SEASON : has_season_stats
    PLAYERS ||--o{ WRTE_STATS_CAREER : has_career_stats
    PLAYERS ||--o{ DEF_STATS_SEASON : has_season_stats
    PLAYERS ||--o{ DEF_STATS_CAREER : has_career_stats
    PLAYERS ||--o{ STATS_SPECIAL_SEASON : has_special_stats
    PLAYERS ||--o{ NEXTGEN_STATS_SEASON : tracked_by
    PLAYERS ||--o{ NEXTGEN_STATS_POST : tracked_by
    PLAYERS ||--o{ NEXTGEN_STATS_CAREER : tracked_by
    PLAYERS ||--o{ CONTRACTS_QB : signed_contract
    PLAYERS ||--o{ DEPTH_CHARTS : assigned_to
    PLAYERS ||--o{ INJURIES_WEEKLY : injured_in
    TEAMS ||--o{ ROSTERS : has_player
    TEAMS ||--o{ GAMES : played_at
    TEAMS ||--o{ QB_STATS_WEEKLY : team_stats
    TEAMS ||--o{ INJURIES_WEEKLY : reports_injury
    TEAMS ||--o{ PARTICIPATION_OFFENSE_GAME : participated_in
    TEAMS ||--o{ PARTICIPATION_DEFENSE_GAME : participated_in
    TEAMS ||--o{ DEPTH_CHARTS : manages
    TEAMS ||--o{ CONTRACTS_POSITION_CAP : spends
    TEAMS ||--o{ PBP : offense_pbp
    TEAMS ||--o{ PBP : defense_pbp
    TEAMS ||--o{ INJURIES_TEAM_WEEKLY : weekly_injuries
    TEAMS ||--o{ INJURIES_TEAM_SEASON : season_injuries
    TEAMS ||--o{ INJURIES_POSITION_WEEKLY : position_injuries
    GAMES ||--o{ PBP : has_play
    GAMES ||--o{ PARTICIPATION_OFFENSE_PBP : tracks_offense
    GAMES ||--o{ PARTICIPATION_DEFENSE_PBP : tracks_defense
    GAMES ||--o{ QB_STATS_WEEKLY : summarized_in
    GAMES ||--o{ DEF_STATS_WEEKLY : summarized_in
    GAMES ||--o{ PARTICIPATION_OFFENSE_GAME : rolled_up_to
    GAMES ||--o{ PARTICIPATION_DEFENSE_GAME : rolled_up_to
    ROSTERS ||--|| ROSTER_SUMMARY : summarized_to
    ROSTERS ||--|| ROSTER_POSITION_SUMMARY : position_summary
    PLAYERS ||--o{ SNAPCOUNT_WEEKLY : records_snaps
    PLAYERS ||--o{ SNAPCOUNT_SEASON : records_snaps
    PLAYERS ||--o{ SNAPCOUNT_CAREER : records_snaps
    PLAYERS ||--o{ ESPN_QBR_SEASON : has_qbr
    PLAYERS ||--o{ ESPN_QBR_CAREER : has_qbr
    TEAMS ||--o{ SNAPCOUNT_WEEKLY : team_snaps
    TEAMS ||--o{ SNAPCOUNT_SEASON : team_snaps
    TEAMS ||--o{ SNAPCOUNT_CAREER : team_snaps
    TEAMS ||--o{ TEAM_METADATA : has_metadata
    PLAYERS ||--|| ID_MAP : identified_by

    %% ENTITIES
    PLAYERS {
      string player_id PK
      string full_name
    }
    TEAMS {
      string team_id PK
      string team_name
    }
    GAMES {
      string game_id PK
      int season
      int week
    }
    ROSTERS {
      string player_id FK
      string team_id FK
      int season
      int week
    }
    QB_STATS_WEEKLY {
      int season
      int week
      string player_id FK
      string position
      string recent_team
    }
    RB_STATS_WEEKLY {
      int season
      int week
      string player_id FK
      string recent_team
    }
    WRTE_STATS_WEEKLY {
      int season
      int week
      string player_id FK
      string position
    }
    DEF_STATS_WEEKLY {
      int season
      int week
      string player_id FK
    }
    STATS_SPECIAL_WEEKLY {
      int season
      int week
      string player_id FK
    }
    NEXTGEN_STATS_WEEKLY {
      int season
      string season_type
      int week
      string player_gsis_id FK
    }
    QB_STATS_SEASON {
      int season
      string player_id FK
      string position
      string recent_team
    }
    RB_STATS_SEASON {
      int season
      string player_id FK
      string recent_team
    }
    WRTE_STATS_SEASON {
      int season
      string player_id FK
      string position
    }
    DEF_STATS_SEASON {
      int season
      string player_id FK
    }
    STATS_SPECIAL_SEASON {
      int season
      string player_id FK
    }
    QB_STATS_CAREER {
      string player_id PK
      string position
      string recent_team
    }
    RB_STATS_CAREER {
      string player_id PK
      string recent_team
    }
    WRTE_STATS_CAREER {
      string player_id PK
      string position
    }
    DEF_STATS_CAREER {
      string player_id PK
    }
    NEXTGEN_STATS_SEASON {
      int season
      string player_gsis_id FK
    }
    NEXTGEN_STATS_POST {
      string player_gsis_id FK
    }
    NEXTGEN_STATS_CAREER {
      string player_gsis_id PK
    }

    PARTICIPATION_OFFENSE_PBP {
      string game_id FK
      int play_id
      string team
    }
    PARTICIPATION_DEFENSE_PBP {
      string game_id FK
      int play_id
      string defense_team
    }
    PARTICIPATION_OFFENSE_GAME {
      string game_id FK
      string team
    }
    PARTICIPATION_DEFENSE_GAME {
      string game_id FK
      string defense_team
    }
    PARTICIPATION_OFFENSE_SEASON {
      int season
      string team
    }
    PARTICIPATION_DEFENSE_SEASON {
      int season
      string defense_team
    }
    DEPTH_CHARTS {
      int season
      int week
      string team
      string player_id
      string position
    }
    INJURIES_WEEKLY {
      int season
      int week
      string team
      string gsis_id
      string report_status
    }
    INJURIES_TEAM_WEEKLY {
      int season
      int week
      string team
      int weekly_injuries
      int cumulative_injuries
    }
    INJURIES_TEAM_SEASON {
      int season
      string team
      int season_injuries
    }
    INJURIES_POSITION_WEEKLY {
      int season
      int week
      string team
      string position
      int position_injuries
      int cumulative_position_injuries
    }
    CONTRACTS_QB {
      int contract_id PK
      string gsis_id
      string player
      string team
      int year_signed
      int contract_start
      int contract_end
      float apy_cap_pct
    }
    CONTRACTS_POSITION_CAP {
      string position
      int year_signed
      string team
      float avg_apy_cap_pct
      float total_apy
      int count
    }
    PBP {
      string game_id FK
      int play_id
      int qtr
      int down
      int ydstogo
      int yardline_100
      string posteam
      string defteam
      string play_type
      float epa
      int success
      int touchdown
      int interception
      int penalty
      int pass
      int rush
      int special
    }
    TEAM_METADATA {
      string team_id PK
      string team_abbr
      string team_name
      string team_nick
      string team_conf
      string team_division
      string team_color
      string team_color2
      string team_color3
      string team_color4
      string team_logo_wikipedia
      string team_logo_espn
      string team_wordmark
      string team_conference_logo
      string team_league_logo
      string team_logo_squared
    }

    ID_MAP {
      string full_name
      string first_name
      string last_name
      string gsis_id
      string espn_id
      string sportradar_id
      string yahoo_id
      string rotowire_id
      string pff_id
      string pfr_id
      string fantasy_data_id
      string sleeper_id
      string esb_id
      string gsis_it_id
      string smart_id
    }

    SNAPCOUNT_WEEKLY {
      string game_id FK
      string team FK
      string player FK
      string position
      int season
      int week
      string opponent
      double offense_snaps
      double offense_pct
      double defense_snaps
      double defense_pct
      double st_snaps
      double st_pct
    }

    SNAPCOUNT_SEASON {
      string team FK
      string player FK
      string position
      int season
      int games_played
      int offense_games
      int defense_games
      int st_games
      double offense_snaps
      double defense_snaps
      double st_snaps
      double offense_pct_mean
      double defense_pct_mean
      double st_pct_mean
    }

    SNAPCOUNT_CAREER {
      string player FK
      string position
      int first_season
      int last_season
      int seasons_played
      int teams_played_for
      int games_played
      int offense_games
      int defense_games
      int st_games
      double offense_snaps
      double defense_snaps
      double st_snaps
      double offense_pct_mean
      double defense_pct_mean
      double st_pct_mean
    }

    ESPN_QBR_SEASON {
      int season
      string season_type
      string game_week
      string team_abb
      string player_id FK
      string name_short
      int rank
      double qbr_total
      double pts_added
      double qb_plays
      double epa_total
      double pass
      double run
      double exp_sack
      double penalty
      double qbr_raw
      double sack
      string name_first
      string name_last
      string name_display
      string headshot_href
      string team
      boolean qualified
    }

    ESPN_QBR_CAREER {
      string player_id FK
      string name_display
      string season_type
      int first_season
      int last_season
      int seasons_played
      int teams_played_for
      double qb_plays
      double qbr_total_w
      double qbr_raw_w
      double pts_added
      double epa
      double pass
      double run
      double sack
      double exp_sack
      double penalty
      int qualified_seasons
    }