name: test-coverage

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install deps (incl. covr)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"hard"'
          extra-packages: any::covr
          needs: coverage

      - name: Run testthat & write Cobertura XML
        run: |
          Rscript -e 'cov <- covr::package_coverage(); covr::to_cobertura(cov, "coverage.xml"); print(cov)'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.NFLMODELER_CODECOV }}
          files: coverage.xml
          flags: r-testthat
          fail_ci_if_error: true
