name: test-coverage

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up R dependencies (incl. covr)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      - name: Run tests & compute coverage (Cobertura XML)
        run: |
          Rscript -e 'cov <- covr::package_coverage(); covr::to_cobertura(cov, "coverage.xml"); print(cov)'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          flags: unittests
          fail_ci_if_error: true
          token: ${{ secrets.NFLMODELER_CODECOV }}